-- Migration 055: server-authoritative RANDOM spawn. Idempotent.
-- ╔═══════════════════════════════════════════════════════════════════════════╗
-- ║  THE FIX: stop players "placing themselves anywhere" in CP War.               ║
-- ║                                                                              ║
-- ║  Until now the spawn REGION was chosen by the client and merely validated     ║
-- ║  server-side as "unclaimed" (war_spawn, migration 028/047; war_buy_units      ║
-- ║  respawn, migration 052). Randomness lived ONLY in the client (pickRandom-     ║
-- ║  Spawn). Because the anon key ships in the public bundle, anyone could call    ║
-- ║  war_spawn / war_buy_units with ANY unclaimed region_id and land exactly       ║
-- ║  where they wanted. This migration moves the random pick to the SERVER.        ║
-- ║                                                                              ║
-- ║  The province graph is a client asset and was not in the DB, so the server     ║
-- ║  had no region universe to pick from. We seed it here as war_region_pool      ║
-- ║  (generated from public/war/provinces.json — RE-SEED if the map changes).      ║
-- ╚═══════════════════════════════════════════════════════════════════════════╝

-- ── 1) Region universe (the spawn pool) ──────────────────────────────────────
create table if not exists public.war_region_pool (
  region_id text primary key,
  country   text
);
alter table public.war_region_pool enable row level security;
drop policy if exists war_region_pool_read on public.war_region_pool;
create policy war_region_pool_read on public.war_region_pool
  for select using (auth.role() = 'authenticated');

-- Seed / refresh all 1027 regions. Idempotent.
insert into public.war_region_pool (region_id, country) values
  ('ABW_NE', 'Aruba'),
  ('ABW_NW', 'Aruba'),
  ('ABW_SE', 'Aruba'),
  ('ABW_SW', 'Aruba'),
  ('AFG_NE', 'Afghanistan'),
  ('AFG_NW', 'Afghanistan'),
  ('AFG_SE', 'Afghanistan'),
  ('AFG_SW', 'Afghanistan'),
  ('AGO_NE', 'Angola'),
  ('AGO_NW', 'Angola'),
  ('AGO_SE', 'Angola'),
  ('AGO_SW', 'Angola'),
  ('AIA_NE', 'Anguilla'),
  ('AIA_NW', 'Anguilla'),
  ('AIA_SE', 'Anguilla'),
  ('AIA_SW', 'Anguilla'),
  ('ALB_NE', 'Albania'),
  ('ALB_NW', 'Albania'),
  ('ALB_SE', 'Albania'),
  ('ALB_SW', 'Albania'),
  ('ALD_NE', 'Åland'),
  ('ALD_NW', 'Åland'),
  ('ALD_SE', 'Åland'),
  ('ALD_SW', 'Åland'),
  ('AND_NE', 'Andorra'),
  ('AND_NW', 'Andorra'),
  ('AND_SE', 'Andorra'),
  ('AND_SW', 'Andorra'),
  ('ARE_NE', 'United Arab Emirates'),
  ('ARE_NW', 'United Arab Emirates'),
  ('ARE_SE', 'United Arab Emirates'),
  ('ARE_SW', 'United Arab Emirates'),
  ('ARG_NE', 'Argentina'),
  ('ARG_NW', 'Argentina'),
  ('ARG_SE', 'Argentina'),
  ('ARG_SW', 'Argentina'),
  ('ARM_NE', 'Armenia'),
  ('ARM_NW', 'Armenia'),
  ('ARM_SE', 'Armenia'),
  ('ARM_SW', 'Armenia'),
  ('ASM_NE', 'American Samoa'),
  ('ASM_NW', 'American Samoa'),
  ('ASM_SE', 'American Samoa'),
  ('ASM_SW', 'American Samoa'),
  ('ATC_NE', 'Ashmore and Cartier Is.'),
  ('ATC_NW', 'Ashmore and Cartier Is.'),
  ('ATC_SE', 'Ashmore and Cartier Is.'),
  ('ATC_SW', 'Ashmore and Cartier Is.'),
  ('ATF_NE', 'Fr. S. Antarctic Lands'),
  ('ATF_NW', 'Fr. S. Antarctic Lands'),
  ('ATF_SE', 'Fr. S. Antarctic Lands'),
  ('ATF_SW', 'Fr. S. Antarctic Lands'),
  ('ATG_NE', 'Antigua and Barb.'),
  ('ATG_NW', 'Antigua and Barb.'),
  ('ATG_SE', 'Antigua and Barb.'),
  ('ATG_SW', 'Antigua and Barb.'),
  ('AUS_NE', 'Australia'),
  ('AUS_NW', 'Australia'),
  ('AUS_SE', 'Australia'),
  ('AUS_SW', 'Australia'),
  ('AUT_NE', 'Austria'),
  ('AUT_NW', 'Austria'),
  ('AUT_SE', 'Austria'),
  ('AUT_SW', 'Austria'),
  ('AZE_NE', 'Azerbaijan'),
  ('AZE_NW', 'Azerbaijan'),
  ('AZE_SE', 'Azerbaijan'),
  ('AZE_SW', 'Azerbaijan'),
  ('BDI_NE', 'Burundi'),
  ('BDI_NW', 'Burundi'),
  ('BDI_SE', 'Burundi'),
  ('BDI_SW', 'Burundi'),
  ('BEL_NE', 'Belgium'),
  ('BEL_NW', 'Belgium'),
  ('BEL_SE', 'Belgium'),
  ('BEL_SW', 'Belgium'),
  ('BEN_NE', 'Benin'),
  ('BEN_NW', 'Benin'),
  ('BEN_SE', 'Benin'),
  ('BEN_SW', 'Benin'),
  ('BFA_NE', 'Burkina Faso'),
  ('BFA_NW', 'Burkina Faso'),
  ('BFA_SE', 'Burkina Faso'),
  ('BFA_SW', 'Burkina Faso'),
  ('BGD_NE', 'Bangladesh'),
  ('BGD_NW', 'Bangladesh'),
  ('BGD_SE', 'Bangladesh'),
  ('BGD_SW', 'Bangladesh'),
  ('BGR_NE', 'Bulgaria'),
  ('BGR_NW', 'Bulgaria'),
  ('BGR_SE', 'Bulgaria'),
  ('BGR_SW', 'Bulgaria'),
  ('BHR_NE', 'Bahrain'),
  ('BHR_NW', 'Bahrain'),
  ('BHR_SE', 'Bahrain'),
  ('BHR_SW', 'Bahrain'),
  ('BHS_NE', 'Bahamas'),
  ('BHS_NW', 'Bahamas'),
  ('BHS_SE', 'Bahamas'),
  ('BHS_SW', 'Bahamas'),
  ('BIH_NE', 'Bosnia and Herz.'),
  ('BIH_NW', 'Bosnia and Herz.'),
  ('BIH_SE', 'Bosnia and Herz.'),
  ('BIH_SW', 'Bosnia and Herz.'),
  ('BJN_NE', 'Bajo Nuevo Bank'),
  ('BJN_NW', 'Bajo Nuevo Bank'),
  ('BJN_SE', 'Bajo Nuevo Bank'),
  ('BJN_SW', 'Bajo Nuevo Bank'),
  ('BLM_NE', 'St-Barthélemy'),
  ('BLM_NW', 'St-Barthélemy'),
  ('BLM_SE', 'St-Barthélemy'),
  ('BLM_SW', 'St-Barthélemy'),
  ('BLR_NE', 'Belarus'),
  ('BLR_NW', 'Belarus'),
  ('BLR_SE', 'Belarus'),
  ('BLR_SW', 'Belarus'),
  ('BLZ_NE', 'Belize'),
  ('BLZ_NW', 'Belize'),
  ('BLZ_SE', 'Belize'),
  ('BLZ_SW', 'Belize'),
  ('BMU_NE', 'Bermuda'),
  ('BMU_NW', 'Bermuda'),
  ('BMU_SE', 'Bermuda'),
  ('BMU_SW', 'Bermuda'),
  ('BOL_NE', 'Bolivia'),
  ('BOL_NW', 'Bolivia'),
  ('BOL_SE', 'Bolivia'),
  ('BOL_SW', 'Bolivia'),
  ('BRA_NE', 'Brazil'),
  ('BRA_NW', 'Brazil'),
  ('BRA_SE', 'Brazil'),
  ('BRA_SW', 'Brazil'),
  ('BRB_NE', 'Barbados'),
  ('BRB_NW', 'Barbados'),
  ('BRB_SE', 'Barbados'),
  ('BRB_SW', 'Barbados'),
  ('BRI_NE', 'Brazilian I.'),
  ('BRI_NW', 'Brazilian I.'),
  ('BRI_SE', 'Brazilian I.'),
  ('BRI_SW', 'Brazilian I.'),
  ('BRN_NE', 'Brunei'),
  ('BRN_NW', 'Brunei'),
  ('BRN_SE', 'Brunei'),
  ('BRN_SW', 'Brunei'),
  ('BRT_NE', 'Bir Tawil'),
  ('BRT_NW', 'Bir Tawil'),
  ('BRT_SE', 'Bir Tawil'),
  ('BRT_SW', 'Bir Tawil'),
  ('BTN_NE', 'Bhutan'),
  ('BTN_NW', 'Bhutan'),
  ('BTN_SE', 'Bhutan'),
  ('BTN_SW', 'Bhutan'),
  ('BWA_NE', 'Botswana'),
  ('BWA_NW', 'Botswana'),
  ('BWA_SE', 'Botswana'),
  ('BWA_SW', 'Botswana'),
  ('CAF_NE', 'Central African Rep.'),
  ('CAF_NW', 'Central African Rep.'),
  ('CAF_SE', 'Central African Rep.'),
  ('CAF_SW', 'Central African Rep.'),
  ('CAN_NE', 'Canada'),
  ('CAN_NW', 'Canada'),
  ('CAN_SE', 'Canada'),
  ('CAN_SW', 'Canada'),
  ('CHE_NE', 'Switzerland'),
  ('CHE_NW', 'Switzerland'),
  ('CHE_SE', 'Switzerland'),
  ('CHE_SW', 'Switzerland'),
  ('CHL_NE', 'Chile'),
  ('CHL_NW', 'Chile'),
  ('CHL_SE', 'Chile'),
  ('CHL_SW', 'Chile'),
  ('CHN_NE', 'China'),
  ('CHN_NW', 'China'),
  ('CHN_SE', 'China'),
  ('CHN_SW', 'China'),
  ('CIV_NE', 'Côte d''Ivoire'),
  ('CIV_NW', 'Côte d''Ivoire'),
  ('CIV_SE', 'Côte d''Ivoire'),
  ('CIV_SW', 'Côte d''Ivoire'),
  ('CLP_NE', 'Clipperton I.'),
  ('CLP_NW', 'Clipperton I.'),
  ('CLP_SE', 'Clipperton I.'),
  ('CLP_SW', 'Clipperton I.'),
  ('CMR_NE', 'Cameroon'),
  ('CMR_NW', 'Cameroon'),
  ('CMR_SE', 'Cameroon'),
  ('CMR_SW', 'Cameroon'),
  ('CNM_NE', 'Cyprus U.N. Buffer Zone'),
  ('CNM_NW', 'Cyprus U.N. Buffer Zone'),
  ('CNM_SE', 'Cyprus U.N. Buffer Zone'),
  ('CNM_SW', 'Cyprus U.N. Buffer Zone'),
  ('COD_NE', 'Dem. Rep. Congo'),
  ('COD_NW', 'Dem. Rep. Congo'),
  ('COD_SE', 'Dem. Rep. Congo'),
  ('COD_SW', 'Dem. Rep. Congo'),
  ('COG_NE', 'Congo'),
  ('COG_NW', 'Congo'),
  ('COG_SE', 'Congo'),
  ('COG_SW', 'Congo'),
  ('COK_NE', 'Cook Is.'),
  ('COK_NW', 'Cook Is.'),
  ('COK_SE', 'Cook Is.'),
  ('COK_SW', 'Cook Is.'),
  ('COL_NE', 'Colombia'),
  ('COL_NW', 'Colombia'),
  ('COL_SE', 'Colombia'),
  ('COL_SW', 'Colombia'),
  ('COM_NE', 'Comoros'),
  ('COM_NW', 'Comoros'),
  ('COM_SE', 'Comoros'),
  ('COM_SW', 'Comoros'),
  ('CPV_NE', 'Cabo Verde'),
  ('CPV_NW', 'Cabo Verde'),
  ('CPV_SE', 'Cabo Verde'),
  ('CPV_SW', 'Cabo Verde'),
  ('CRI_NE', 'Costa Rica'),
  ('CRI_NW', 'Costa Rica'),
  ('CRI_SE', 'Costa Rica'),
  ('CRI_SW', 'Costa Rica'),
  ('CSI_NE', 'Coral Sea Is.'),
  ('CSI_NW', 'Coral Sea Is.'),
  ('CSI_SE', 'Coral Sea Is.'),
  ('CSI_SW', 'Coral Sea Is.'),
  ('CUB_NE', 'Cuba'),
  ('CUB_NW', 'Cuba'),
  ('CUB_SE', 'Cuba'),
  ('CUB_SW', 'Cuba'),
  ('CUW_NE', 'Curaçao'),
  ('CUW_NW', 'Curaçao'),
  ('CUW_SE', 'Curaçao'),
  ('CUW_SW', 'Curaçao'),
  ('CYM_NE', 'Cayman Is.'),
  ('CYM_NW', 'Cayman Is.'),
  ('CYM_SE', 'Cayman Is.'),
  ('CYM_SW', 'Cayman Is.'),
  ('CYN_NE', 'N. Cyprus'),
  ('CYN_NW', 'N. Cyprus'),
  ('CYN_SE', 'N. Cyprus'),
  ('CYN_SW', 'N. Cyprus'),
  ('CYP_NE', 'Cyprus'),
  ('CYP_NW', 'Cyprus'),
  ('CYP_SE', 'Cyprus'),
  ('CYP_SW', 'Cyprus'),
  ('CZE_NE', 'Czechia'),
  ('CZE_NW', 'Czechia'),
  ('CZE_SE', 'Czechia'),
  ('CZE_SW', 'Czechia'),
  ('DEU_NE', 'Germany'),
  ('DEU_NW', 'Germany'),
  ('DEU_SE', 'Germany'),
  ('DEU_SW', 'Germany'),
  ('DJI_NE', 'Djibouti'),
  ('DJI_NW', 'Djibouti'),
  ('DJI_SE', 'Djibouti'),
  ('DJI_SW', 'Djibouti'),
  ('DMA_NE', 'Dominica'),
  ('DMA_NW', 'Dominica'),
  ('DMA_SE', 'Dominica'),
  ('DMA_SW', 'Dominica'),
  ('DNK_NE', 'Denmark'),
  ('DNK_NW', 'Denmark'),
  ('DNK_SE', 'Denmark'),
  ('DNK_SW', 'Denmark'),
  ('DOM_NE', 'Dominican Rep.'),
  ('DOM_NW', 'Dominican Rep.'),
  ('DOM_SE', 'Dominican Rep.'),
  ('DOM_SW', 'Dominican Rep.'),
  ('DZA_NE', 'Algeria'),
  ('DZA_NW', 'Algeria'),
  ('DZA_SE', 'Algeria'),
  ('DZA_SW', 'Algeria'),
  ('ECU_NE', 'Ecuador'),
  ('ECU_NW', 'Ecuador'),
  ('ECU_SE', 'Ecuador'),
  ('ECU_SW', 'Ecuador'),
  ('EGY_NE', 'Egypt'),
  ('EGY_NW', 'Egypt'),
  ('EGY_SE', 'Egypt'),
  ('EGY_SW', 'Egypt'),
  ('ERI_NE', 'Eritrea'),
  ('ERI_NW', 'Eritrea'),
  ('ERI_SE', 'Eritrea'),
  ('ERI_SW', 'Eritrea'),
  ('ESB_NE', 'Dhekelia'),
  ('ESB_NW', 'Dhekelia'),
  ('ESB_SE', 'Dhekelia'),
  ('ESB_SW', 'Dhekelia'),
  ('ESP_NE', 'Spain'),
  ('ESP_NW', 'Spain'),
  ('ESP_SE', 'Spain'),
  ('ESP_SW', 'Spain'),
  ('EST_NE', 'Estonia'),
  ('EST_NW', 'Estonia'),
  ('EST_SE', 'Estonia'),
  ('EST_SW', 'Estonia'),
  ('ETH_NE', 'Ethiopia'),
  ('ETH_NW', 'Ethiopia'),
  ('ETH_SE', 'Ethiopia'),
  ('ETH_SW', 'Ethiopia'),
  ('FIN_NE', 'Finland'),
  ('FIN_NW', 'Finland'),
  ('FIN_SE', 'Finland'),
  ('FIN_SW', 'Finland'),
  ('FJI_NE', 'Fiji'),
  ('FJI_NW', 'Fiji'),
  ('FJI_SE', 'Fiji'),
  ('FJI_SW', 'Fiji'),
  ('FLK_NE', 'Falkland Is.'),
  ('FLK_NW', 'Falkland Is.'),
  ('FLK_SE', 'Falkland Is.'),
  ('FLK_SW', 'Falkland Is.'),
  ('FRA_NE', 'France'),
  ('FRA_NW', 'France'),
  ('FRA_SE', 'France'),
  ('FRA_SW', 'France'),
  ('FRO_NE', 'Faeroe Is.'),
  ('FRO_NW', 'Faeroe Is.'),
  ('FRO_SE', 'Faeroe Is.'),
  ('FRO_SW', 'Faeroe Is.'),
  ('FSM_NE', 'Micronesia'),
  ('FSM_NW', 'Micronesia'),
  ('FSM_SE', 'Micronesia'),
  ('FSM_SW', 'Micronesia'),
  ('GAB_NE', 'Gabon'),
  ('GAB_NW', 'Gabon'),
  ('GAB_SE', 'Gabon'),
  ('GAB_SW', 'Gabon'),
  ('GBR_NE', 'United Kingdom'),
  ('GBR_NW', 'United Kingdom'),
  ('GBR_SE', 'United Kingdom'),
  ('GBR_SW', 'United Kingdom'),
  ('GEO_NE', 'Georgia'),
  ('GEO_NW', 'Georgia'),
  ('GEO_SE', 'Georgia'),
  ('GEO_SW', 'Georgia'),
  ('GGY_NE', 'Guernsey'),
  ('GGY_NW', 'Guernsey'),
  ('GGY_SE', 'Guernsey'),
  ('GGY_SW', 'Guernsey'),
  ('GHA_NE', 'Ghana'),
  ('GHA_NW', 'Ghana'),
  ('GHA_SE', 'Ghana'),
  ('GHA_SW', 'Ghana'),
  ('GIB_NE', 'Gibraltar'),
  ('GIB_NW', 'Gibraltar'),
  ('GIB_SE', 'Gibraltar'),
  ('GIB_SW', 'Gibraltar'),
  ('GIN_NE', 'Guinea'),
  ('GIN_NW', 'Guinea'),
  ('GIN_SE', 'Guinea'),
  ('GIN_SW', 'Guinea'),
  ('GMB_NE', 'Gambia'),
  ('GMB_NW', 'Gambia'),
  ('GMB_SE', 'Gambia'),
  ('GMB_SW', 'Gambia'),
  ('GNB_NE', 'Guinea-Bissau'),
  ('GNB_NW', 'Guinea-Bissau'),
  ('GNB_SE', 'Guinea-Bissau'),
  ('GNB_SW', 'Guinea-Bissau'),
  ('GNQ_NE', 'Eq. Guinea'),
  ('GNQ_NW', 'Eq. Guinea'),
  ('GNQ_SE', 'Eq. Guinea'),
  ('GNQ_SW', 'Eq. Guinea'),
  ('GRC_NE', 'Greece'),
  ('GRC_NW', 'Greece'),
  ('GRC_SE', 'Greece'),
  ('GRC_SW', 'Greece'),
  ('GRD_NE', 'Grenada'),
  ('GRD_NW', 'Grenada'),
  ('GRD_SE', 'Grenada'),
  ('GRD_SW', 'Grenada'),
  ('GRL_NE', 'Greenland'),
  ('GRL_NW', 'Greenland'),
  ('GRL_SE', 'Greenland'),
  ('GRL_SW', 'Greenland'),
  ('GTM_NE', 'Guatemala'),
  ('GTM_NW', 'Guatemala'),
  ('GTM_SE', 'Guatemala'),
  ('GTM_SW', 'Guatemala'),
  ('GUM_NE', 'Guam'),
  ('GUM_NW', 'Guam'),
  ('GUM_SE', 'Guam'),
  ('GUM_SW', 'Guam'),
  ('GUY_NE', 'Guyana'),
  ('GUY_NW', 'Guyana'),
  ('GUY_SE', 'Guyana'),
  ('GUY_SW', 'Guyana'),
  ('HKG_NE', 'Hong Kong'),
  ('HKG_NW', 'Hong Kong'),
  ('HKG_SE', 'Hong Kong'),
  ('HKG_SW', 'Hong Kong'),
  ('HMD_NE', 'Heard I. and McDonald Is.'),
  ('HMD_NW', 'Heard I. and McDonald Is.'),
  ('HMD_SE', 'Heard I. and McDonald Is.'),
  ('HMD_SW', 'Heard I. and McDonald Is.'),
  ('HND_NE', 'Honduras'),
  ('HND_NW', 'Honduras'),
  ('HND_SE', 'Honduras'),
  ('HND_SW', 'Honduras'),
  ('HRV_NE', 'Croatia'),
  ('HRV_NW', 'Croatia'),
  ('HRV_SE', 'Croatia'),
  ('HRV_SW', 'Croatia'),
  ('HTI_NE', 'Haiti'),
  ('HTI_NW', 'Haiti'),
  ('HTI_SE', 'Haiti'),
  ('HTI_SW', 'Haiti'),
  ('HUN_NE', 'Hungary'),
  ('HUN_NW', 'Hungary'),
  ('HUN_SE', 'Hungary'),
  ('HUN_SW', 'Hungary'),
  ('IDN_NE', 'Indonesia'),
  ('IDN_NW', 'Indonesia'),
  ('IDN_SE', 'Indonesia'),
  ('IDN_SW', 'Indonesia'),
  ('IMN_NE', 'Isle of Man'),
  ('IMN_NW', 'Isle of Man'),
  ('IMN_SE', 'Isle of Man'),
  ('IMN_SW', 'Isle of Man'),
  ('IND_NE', 'India'),
  ('IND_NW', 'India'),
  ('IND_SE', 'India'),
  ('IND_SW', 'India'),
  ('IOA_NE', 'Indian Ocean Ter.'),
  ('IOA_NW', 'Indian Ocean Ter.'),
  ('IOA_SE', 'Indian Ocean Ter.'),
  ('IOA_SW', 'Indian Ocean Ter.'),
  ('IOT_NE', 'Br. Indian Ocean Ter.'),
  ('IOT_NW', 'Br. Indian Ocean Ter.'),
  ('IOT_SE', 'Br. Indian Ocean Ter.'),
  ('IOT_SW', 'Br. Indian Ocean Ter.'),
  ('IRL_NE', 'Ireland'),
  ('IRL_NW', 'Ireland'),
  ('IRL_SE', 'Ireland'),
  ('IRL_SW', 'Ireland'),
  ('IRN_NE', 'Iran'),
  ('IRN_NW', 'Iran'),
  ('IRN_SE', 'Iran'),
  ('IRN_SW', 'Iran'),
  ('IRQ_NE', 'Iraq'),
  ('IRQ_NW', 'Iraq'),
  ('IRQ_SE', 'Iraq'),
  ('IRQ_SW', 'Iraq'),
  ('ISL_NE', 'Iceland'),
  ('ISL_NW', 'Iceland'),
  ('ISL_SE', 'Iceland'),
  ('ISL_SW', 'Iceland'),
  ('ISR_NE', 'Israel'),
  ('ISR_NW', 'Israel'),
  ('ISR_SE', 'Israel'),
  ('ISR_SW', 'Israel'),
  ('ITA_NE', 'Italy'),
  ('ITA_NW', 'Italy'),
  ('ITA_SE', 'Italy'),
  ('ITA_SW', 'Italy'),
  ('JAM_NE', 'Jamaica'),
  ('JAM_NW', 'Jamaica'),
  ('JAM_SE', 'Jamaica'),
  ('JAM_SW', 'Jamaica'),
  ('JEY_NE', 'Jersey'),
  ('JEY_NW', 'Jersey'),
  ('JEY_SE', 'Jersey'),
  ('JEY_SW', 'Jersey'),
  ('JOR_NE', 'Jordan'),
  ('JOR_NW', 'Jordan'),
  ('JOR_SE', 'Jordan'),
  ('JOR_SW', 'Jordan'),
  ('JPN_NE', 'Japan'),
  ('JPN_NW', 'Japan'),
  ('JPN_SE', 'Japan'),
  ('JPN_SW', 'Japan'),
  ('KAB_NE', 'Baikonur'),
  ('KAB_NW', 'Baikonur'),
  ('KAB_SE', 'Baikonur'),
  ('KAB_SW', 'Baikonur'),
  ('KAS_NE', 'Siachen Glacier'),
  ('KAS_NW', 'Siachen Glacier'),
  ('KAS_SE', 'Siachen Glacier'),
  ('KAS_SW', 'Siachen Glacier'),
  ('KAZ_NE', 'Kazakhstan'),
  ('KAZ_NW', 'Kazakhstan'),
  ('KAZ_SE', 'Kazakhstan'),
  ('KAZ_SW', 'Kazakhstan'),
  ('KEN_NE', 'Kenya'),
  ('KEN_NW', 'Kenya'),
  ('KEN_SE', 'Kenya'),
  ('KEN_SW', 'Kenya'),
  ('KGZ_NE', 'Kyrgyzstan'),
  ('KGZ_NW', 'Kyrgyzstan'),
  ('KGZ_SE', 'Kyrgyzstan'),
  ('KGZ_SW', 'Kyrgyzstan'),
  ('KHM_NE', 'Cambodia'),
  ('KHM_NW', 'Cambodia'),
  ('KHM_SE', 'Cambodia'),
  ('KHM_SW', 'Cambodia'),
  ('KIR_NE', 'Kiribati'),
  ('KIR_NW', 'Kiribati'),
  ('KIR_SE', 'Kiribati'),
  ('KIR_SW', 'Kiribati'),
  ('KNA_NE', 'St. Kitts and Nevis'),
  ('KNA_NW', 'St. Kitts and Nevis'),
  ('KNA_SE', 'St. Kitts and Nevis'),
  ('KNA_SW', 'St. Kitts and Nevis'),
  ('KOR_NE', 'South Korea'),
  ('KOR_NW', 'South Korea'),
  ('KOR_SE', 'South Korea'),
  ('KOR_SW', 'South Korea'),
  ('KOS_NE', 'Kosovo'),
  ('KOS_NW', 'Kosovo'),
  ('KOS_SE', 'Kosovo'),
  ('KOS_SW', 'Kosovo'),
  ('KWT_NE', 'Kuwait'),
  ('KWT_NW', 'Kuwait'),
  ('KWT_SE', 'Kuwait'),
  ('KWT_SW', 'Kuwait'),
  ('LAO_NE', 'Laos'),
  ('LAO_NW', 'Laos'),
  ('LAO_SE', 'Laos'),
  ('LAO_SW', 'Laos'),
  ('LBN_NE', 'Lebanon'),
  ('LBN_NW', 'Lebanon'),
  ('LBN_SE', 'Lebanon'),
  ('LBN_SW', 'Lebanon'),
  ('LBR_NE', 'Liberia'),
  ('LBR_NW', 'Liberia'),
  ('LBR_SE', 'Liberia'),
  ('LBR_SW', 'Liberia'),
  ('LBY_NE', 'Libya'),
  ('LBY_NW', 'Libya'),
  ('LBY_SE', 'Libya'),
  ('LBY_SW', 'Libya'),
  ('LCA_NE', 'Saint Lucia'),
  ('LCA_NW', 'Saint Lucia'),
  ('LCA_SE', 'Saint Lucia'),
  ('LCA_SW', 'Saint Lucia'),
  ('LIE_NE', 'Liechtenstein'),
  ('LIE_NW', 'Liechtenstein'),
  ('LIE_SE', 'Liechtenstein'),
  ('LIE_SW', 'Liechtenstein'),
  ('LKA_NE', 'Sri Lanka'),
  ('LKA_NW', 'Sri Lanka'),
  ('LKA_SE', 'Sri Lanka'),
  ('LKA_SW', 'Sri Lanka'),
  ('LSO_NE', 'Lesotho'),
  ('LSO_NW', 'Lesotho'),
  ('LSO_SE', 'Lesotho'),
  ('LSO_SW', 'Lesotho'),
  ('LTU_NE', 'Lithuania'),
  ('LTU_NW', 'Lithuania'),
  ('LTU_SE', 'Lithuania'),
  ('LTU_SW', 'Lithuania'),
  ('LUX_NE', 'Luxembourg'),
  ('LUX_NW', 'Luxembourg'),
  ('LUX_SE', 'Luxembourg'),
  ('LUX_SW', 'Luxembourg'),
  ('LVA_NE', 'Latvia'),
  ('LVA_NW', 'Latvia'),
  ('LVA_SE', 'Latvia'),
  ('LVA_SW', 'Latvia'),
  ('MAC_NE', 'Macao'),
  ('MAC_NW', 'Macao'),
  ('MAC_SE', 'Macao'),
  ('MAC_SW', 'Macao'),
  ('MAF_NE', 'St-Martin'),
  ('MAF_NW', 'St-Martin'),
  ('MAF_SE', 'St-Martin'),
  ('MAF_SW', 'St-Martin'),
  ('MAR_NE', 'Morocco'),
  ('MAR_NW', 'Morocco'),
  ('MAR_SE', 'Morocco'),
  ('MAR_SW', 'Morocco'),
  ('MCO_NE', 'Monaco'),
  ('MCO_NW', 'Monaco'),
  ('MCO_SE', 'Monaco'),
  ('MCO_SW', 'Monaco'),
  ('MDA_NE', 'Moldova'),
  ('MDA_NW', 'Moldova'),
  ('MDA_SE', 'Moldova'),
  ('MDA_SW', 'Moldova'),
  ('MDG_NE', 'Madagascar'),
  ('MDG_NW', 'Madagascar'),
  ('MDG_SE', 'Madagascar'),
  ('MDG_SW', 'Madagascar'),
  ('MDV_NE', 'Maldives'),
  ('MDV_NW', 'Maldives'),
  ('MDV_SE', 'Maldives'),
  ('MDV_SW', 'Maldives'),
  ('MEX_NE', 'Mexico'),
  ('MEX_NW', 'Mexico'),
  ('MEX_SE', 'Mexico'),
  ('MEX_SW', 'Mexico'),
  ('MHL_NE', 'Marshall Is.'),
  ('MHL_NW', 'Marshall Is.'),
  ('MHL_SW', 'Marshall Is.'),
  ('MKD_NE', 'North Macedonia'),
  ('MKD_NW', 'North Macedonia'),
  ('MKD_SE', 'North Macedonia'),
  ('MKD_SW', 'North Macedonia'),
  ('MLI_NE', 'Mali'),
  ('MLI_NW', 'Mali'),
  ('MLI_SE', 'Mali'),
  ('MLI_SW', 'Mali'),
  ('MLT_NE', 'Malta'),
  ('MLT_NW', 'Malta'),
  ('MLT_SE', 'Malta'),
  ('MLT_SW', 'Malta'),
  ('MMR_NE', 'Myanmar'),
  ('MMR_NW', 'Myanmar'),
  ('MMR_SE', 'Myanmar'),
  ('MMR_SW', 'Myanmar'),
  ('MNE_NE', 'Montenegro'),
  ('MNE_NW', 'Montenegro'),
  ('MNE_SE', 'Montenegro'),
  ('MNE_SW', 'Montenegro'),
  ('MNG_NE', 'Mongolia'),
  ('MNG_NW', 'Mongolia'),
  ('MNG_SE', 'Mongolia'),
  ('MNG_SW', 'Mongolia'),
  ('MNP_NE', 'N. Mariana Is.'),
  ('MNP_NW', 'N. Mariana Is.'),
  ('MNP_SE', 'N. Mariana Is.'),
  ('MNP_SW', 'N. Mariana Is.'),
  ('MOZ_NE', 'Mozambique'),
  ('MOZ_NW', 'Mozambique'),
  ('MOZ_SE', 'Mozambique'),
  ('MOZ_SW', 'Mozambique'),
  ('MRT_NE', 'Mauritania'),
  ('MRT_NW', 'Mauritania'),
  ('MRT_SE', 'Mauritania'),
  ('MRT_SW', 'Mauritania'),
  ('MSR_NE', 'Montserrat'),
  ('MSR_NW', 'Montserrat'),
  ('MSR_SE', 'Montserrat'),
  ('MSR_SW', 'Montserrat'),
  ('MUS_NE', 'Mauritius'),
  ('MUS_NW', 'Mauritius'),
  ('MUS_SE', 'Mauritius'),
  ('MUS_SW', 'Mauritius'),
  ('MWI_NE', 'Malawi'),
  ('MWI_NW', 'Malawi'),
  ('MWI_SE', 'Malawi'),
  ('MWI_SW', 'Malawi'),
  ('MYS_NE', 'Malaysia'),
  ('MYS_NW', 'Malaysia'),
  ('MYS_SE', 'Malaysia'),
  ('MYS_SW', 'Malaysia'),
  ('NAM_NE', 'Namibia'),
  ('NAM_NW', 'Namibia'),
  ('NAM_SE', 'Namibia'),
  ('NAM_SW', 'Namibia'),
  ('NCL_NE', 'New Caledonia'),
  ('NCL_NW', 'New Caledonia'),
  ('NCL_SE', 'New Caledonia'),
  ('NCL_SW', 'New Caledonia'),
  ('NER_NE', 'Niger'),
  ('NER_NW', 'Niger'),
  ('NER_SE', 'Niger'),
  ('NER_SW', 'Niger'),
  ('NFK_NE', 'Norfolk Island'),
  ('NFK_NW', 'Norfolk Island'),
  ('NFK_SE', 'Norfolk Island'),
  ('NFK_SW', 'Norfolk Island'),
  ('NGA_NE', 'Nigeria'),
  ('NGA_NW', 'Nigeria'),
  ('NGA_SE', 'Nigeria'),
  ('NGA_SW', 'Nigeria'),
  ('NIC_NE', 'Nicaragua'),
  ('NIC_NW', 'Nicaragua'),
  ('NIC_SE', 'Nicaragua'),
  ('NIC_SW', 'Nicaragua'),
  ('NIU_NE', 'Niue'),
  ('NIU_NW', 'Niue'),
  ('NIU_SE', 'Niue'),
  ('NIU_SW', 'Niue'),
  ('NLD_NE', 'Netherlands'),
  ('NLD_NW', 'Netherlands'),
  ('NLD_SE', 'Netherlands'),
  ('NLD_SW', 'Netherlands'),
  ('NOR_NE', 'Norway'),
  ('NOR_NW', 'Norway'),
  ('NOR_SE', 'Norway'),
  ('NOR_SW', 'Norway'),
  ('NPL_NE', 'Nepal'),
  ('NPL_NW', 'Nepal'),
  ('NPL_SE', 'Nepal'),
  ('NPL_SW', 'Nepal'),
  ('NRU_NE', 'Nauru'),
  ('NRU_NW', 'Nauru'),
  ('NRU_SE', 'Nauru'),
  ('NRU_SW', 'Nauru'),
  ('NZL_NE', 'New Zealand'),
  ('NZL_NW', 'New Zealand'),
  ('NZL_SE', 'New Zealand'),
  ('NZL_SW', 'New Zealand'),
  ('OMN_NE', 'Oman'),
  ('OMN_NW', 'Oman'),
  ('OMN_SE', 'Oman'),
  ('OMN_SW', 'Oman'),
  ('PAK_NE', 'Pakistan'),
  ('PAK_NW', 'Pakistan'),
  ('PAK_SE', 'Pakistan'),
  ('PAK_SW', 'Pakistan'),
  ('PAN_NE', 'Panama'),
  ('PAN_NW', 'Panama'),
  ('PAN_SE', 'Panama'),
  ('PAN_SW', 'Panama'),
  ('PCN_NE', 'Pitcairn Is.'),
  ('PCN_NW', 'Pitcairn Is.'),
  ('PCN_SE', 'Pitcairn Is.'),
  ('PCN_SW', 'Pitcairn Is.'),
  ('PER_NE', 'Peru'),
  ('PER_NW', 'Peru'),
  ('PER_SE', 'Peru'),
  ('PER_SW', 'Peru'),
  ('PGA_NE', 'Spratly Is.'),
  ('PGA_NW', 'Spratly Is.'),
  ('PGA_SE', 'Spratly Is.'),
  ('PGA_SW', 'Spratly Is.'),
  ('PHL_NE', 'Philippines'),
  ('PHL_NW', 'Philippines'),
  ('PHL_SE', 'Philippines'),
  ('PHL_SW', 'Philippines'),
  ('PLW_NE', 'Palau'),
  ('PLW_NW', 'Palau'),
  ('PLW_SE', 'Palau'),
  ('PLW_SW', 'Palau'),
  ('PNG_NE', 'Papua New Guinea'),
  ('PNG_NW', 'Papua New Guinea'),
  ('PNG_SE', 'Papua New Guinea'),
  ('PNG_SW', 'Papua New Guinea'),
  ('POL_NE', 'Poland'),
  ('POL_NW', 'Poland'),
  ('POL_SE', 'Poland'),
  ('POL_SW', 'Poland'),
  ('PRI_NE', 'Puerto Rico'),
  ('PRI_NW', 'Puerto Rico'),
  ('PRI_SE', 'Puerto Rico'),
  ('PRI_SW', 'Puerto Rico'),
  ('PRK_NE', 'North Korea'),
  ('PRK_NW', 'North Korea'),
  ('PRK_SE', 'North Korea'),
  ('PRK_SW', 'North Korea'),
  ('PRT_NE', 'Portugal'),
  ('PRT_NW', 'Portugal'),
  ('PRT_SE', 'Portugal'),
  ('PRT_SW', 'Portugal'),
  ('PRY_NE', 'Paraguay'),
  ('PRY_NW', 'Paraguay'),
  ('PRY_SE', 'Paraguay'),
  ('PRY_SW', 'Paraguay'),
  ('PSX_NE', 'Palestine'),
  ('PSX_NW', 'Palestine'),
  ('PSX_SE', 'Palestine'),
  ('PSX_SW', 'Palestine'),
  ('PYF_NE', 'Fr. Polynesia'),
  ('PYF_NW', 'Fr. Polynesia'),
  ('PYF_SE', 'Fr. Polynesia'),
  ('PYF_SW', 'Fr. Polynesia'),
  ('QAT_NE', 'Qatar'),
  ('QAT_NW', 'Qatar'),
  ('QAT_SE', 'Qatar'),
  ('QAT_SW', 'Qatar'),
  ('ROU_NE', 'Romania'),
  ('ROU_NW', 'Romania'),
  ('ROU_SE', 'Romania'),
  ('ROU_SW', 'Romania'),
  ('RUS_NE', 'Russia'),
  ('RUS_NW', 'Russia'),
  ('RUS_SE', 'Russia'),
  ('RUS_SW', 'Russia'),
  ('RWA_NE', 'Rwanda'),
  ('RWA_NW', 'Rwanda'),
  ('RWA_SE', 'Rwanda'),
  ('RWA_SW', 'Rwanda'),
  ('SAH_NE', 'W. Sahara'),
  ('SAH_NW', 'W. Sahara'),
  ('SAH_SE', 'W. Sahara'),
  ('SAH_SW', 'W. Sahara'),
  ('SAU_NE', 'Saudi Arabia'),
  ('SAU_NW', 'Saudi Arabia'),
  ('SAU_SE', 'Saudi Arabia'),
  ('SAU_SW', 'Saudi Arabia'),
  ('SCR_NE', 'Scarborough Reef'),
  ('SCR_NW', 'Scarborough Reef'),
  ('SCR_SE', 'Scarborough Reef'),
  ('SCR_SW', 'Scarborough Reef'),
  ('SDN_NE', 'Sudan'),
  ('SDN_NW', 'Sudan'),
  ('SDN_SE', 'Sudan'),
  ('SDN_SW', 'Sudan'),
  ('SDS_NE', 'S. Sudan'),
  ('SDS_NW', 'S. Sudan'),
  ('SDS_SE', 'S. Sudan'),
  ('SDS_SW', 'S. Sudan'),
  ('SEN_NE', 'Senegal'),
  ('SEN_NW', 'Senegal'),
  ('SEN_SE', 'Senegal'),
  ('SEN_SW', 'Senegal'),
  ('SER_NE', 'Serranilla Bank'),
  ('SER_NW', 'Serranilla Bank'),
  ('SER_SE', 'Serranilla Bank'),
  ('SER_SW', 'Serranilla Bank'),
  ('SGP_NE', 'Singapore'),
  ('SGP_NW', 'Singapore'),
  ('SGP_SE', 'Singapore'),
  ('SGP_SW', 'Singapore'),
  ('SGS_NE', 'S. Geo. and the Is.'),
  ('SGS_NW', 'S. Geo. and the Is.'),
  ('SGS_SE', 'S. Geo. and the Is.'),
  ('SGS_SW', 'S. Geo. and the Is.'),
  ('SHN_NE', 'Saint Helena'),
  ('SHN_NW', 'Saint Helena'),
  ('SHN_SE', 'Saint Helena'),
  ('SHN_SW', 'Saint Helena'),
  ('SLB_NE', 'Solomon Is.'),
  ('SLB_NW', 'Solomon Is.'),
  ('SLB_SE', 'Solomon Is.'),
  ('SLB_SW', 'Solomon Is.'),
  ('SLE_NE', 'Sierra Leone'),
  ('SLE_NW', 'Sierra Leone'),
  ('SLE_SE', 'Sierra Leone'),
  ('SLE_SW', 'Sierra Leone'),
  ('SLV_NE', 'El Salvador'),
  ('SLV_NW', 'El Salvador'),
  ('SLV_SE', 'El Salvador'),
  ('SLV_SW', 'El Salvador'),
  ('SMR_NE', 'San Marino'),
  ('SMR_NW', 'San Marino'),
  ('SMR_SE', 'San Marino'),
  ('SMR_SW', 'San Marino'),
  ('SOL_NE', 'Somaliland'),
  ('SOL_NW', 'Somaliland'),
  ('SOL_SE', 'Somaliland'),
  ('SOL_SW', 'Somaliland'),
  ('SOM_NE', 'Somalia'),
  ('SOM_NW', 'Somalia'),
  ('SOM_SE', 'Somalia'),
  ('SOM_SW', 'Somalia'),
  ('SPI_NE', 'Southern Patagonian Ice Field'),
  ('SPI_NW', 'Southern Patagonian Ice Field'),
  ('SPI_SE', 'Southern Patagonian Ice Field'),
  ('SPI_SW', 'Southern Patagonian Ice Field'),
  ('SPM_NE', 'St. Pierre and Miquelon'),
  ('SPM_NW', 'St. Pierre and Miquelon'),
  ('SPM_SE', 'St. Pierre and Miquelon'),
  ('SPM_SW', 'St. Pierre and Miquelon'),
  ('SRB_NE', 'Serbia'),
  ('SRB_NW', 'Serbia'),
  ('SRB_SE', 'Serbia'),
  ('SRB_SW', 'Serbia'),
  ('STP_NE', 'São Tomé and Principe'),
  ('STP_NW', 'São Tomé and Principe'),
  ('STP_SE', 'São Tomé and Principe'),
  ('STP_SW', 'São Tomé and Principe'),
  ('SUR_NE', 'Suriname'),
  ('SUR_NW', 'Suriname'),
  ('SUR_SE', 'Suriname'),
  ('SUR_SW', 'Suriname'),
  ('SVK_NE', 'Slovakia'),
  ('SVK_NW', 'Slovakia'),
  ('SVK_SE', 'Slovakia'),
  ('SVK_SW', 'Slovakia'),
  ('SVN_NE', 'Slovenia'),
  ('SVN_NW', 'Slovenia'),
  ('SVN_SE', 'Slovenia'),
  ('SVN_SW', 'Slovenia'),
  ('SWE_NE', 'Sweden'),
  ('SWE_NW', 'Sweden'),
  ('SWE_SE', 'Sweden'),
  ('SWE_SW', 'Sweden'),
  ('SWZ_NE', 'eSwatini'),
  ('SWZ_NW', 'eSwatini'),
  ('SWZ_SE', 'eSwatini'),
  ('SWZ_SW', 'eSwatini'),
  ('SXM_NE', 'Sint Maarten'),
  ('SXM_NW', 'Sint Maarten'),
  ('SXM_SE', 'Sint Maarten'),
  ('SXM_SW', 'Sint Maarten'),
  ('SYC_NE', 'Seychelles'),
  ('SYC_NW', 'Seychelles'),
  ('SYC_SE', 'Seychelles'),
  ('SYC_SW', 'Seychelles'),
  ('SYR_NE', 'Syria'),
  ('SYR_NW', 'Syria'),
  ('SYR_SE', 'Syria'),
  ('SYR_SW', 'Syria'),
  ('TCA_NE', 'Turks and Caicos Is.'),
  ('TCA_NW', 'Turks and Caicos Is.'),
  ('TCA_SE', 'Turks and Caicos Is.'),
  ('TCA_SW', 'Turks and Caicos Is.'),
  ('TCD_NE', 'Chad'),
  ('TCD_NW', 'Chad'),
  ('TCD_SE', 'Chad'),
  ('TCD_SW', 'Chad'),
  ('TGO_NE', 'Togo'),
  ('TGO_NW', 'Togo'),
  ('TGO_SE', 'Togo'),
  ('TGO_SW', 'Togo'),
  ('THA_NE', 'Thailand'),
  ('THA_NW', 'Thailand'),
  ('THA_SE', 'Thailand'),
  ('THA_SW', 'Thailand'),
  ('TJK_NE', 'Tajikistan'),
  ('TJK_NW', 'Tajikistan'),
  ('TJK_SE', 'Tajikistan'),
  ('TJK_SW', 'Tajikistan'),
  ('TKM_NE', 'Turkmenistan'),
  ('TKM_NW', 'Turkmenistan'),
  ('TKM_SE', 'Turkmenistan'),
  ('TKM_SW', 'Turkmenistan'),
  ('TLS_NE', 'Timor-Leste'),
  ('TLS_NW', 'Timor-Leste'),
  ('TLS_SE', 'Timor-Leste'),
  ('TLS_SW', 'Timor-Leste'),
  ('TON_NE', 'Tonga'),
  ('TON_NW', 'Tonga'),
  ('TON_SE', 'Tonga'),
  ('TON_SW', 'Tonga'),
  ('TTO_NE', 'Trinidad and Tobago'),
  ('TTO_NW', 'Trinidad and Tobago'),
  ('TTO_SE', 'Trinidad and Tobago'),
  ('TTO_SW', 'Trinidad and Tobago'),
  ('TUN_NE', 'Tunisia'),
  ('TUN_NW', 'Tunisia'),
  ('TUN_SE', 'Tunisia'),
  ('TUN_SW', 'Tunisia'),
  ('TUR_NE', 'Turkey'),
  ('TUR_NW', 'Turkey'),
  ('TUR_SE', 'Turkey'),
  ('TUR_SW', 'Turkey'),
  ('TUV_NE', 'Tuvalu'),
  ('TUV_NW', 'Tuvalu'),
  ('TUV_SE', 'Tuvalu'),
  ('TUV_SW', 'Tuvalu'),
  ('TWN_NE', 'Taiwan'),
  ('TWN_NW', 'Taiwan'),
  ('TWN_SE', 'Taiwan'),
  ('TWN_SW', 'Taiwan'),
  ('TZA_NE', 'Tanzania'),
  ('TZA_NW', 'Tanzania'),
  ('TZA_SE', 'Tanzania'),
  ('TZA_SW', 'Tanzania'),
  ('UGA_NE', 'Uganda'),
  ('UGA_NW', 'Uganda'),
  ('UGA_SE', 'Uganda'),
  ('UGA_SW', 'Uganda'),
  ('UKR_NE', 'Ukraine'),
  ('UKR_NW', 'Ukraine'),
  ('UKR_SE', 'Ukraine'),
  ('UKR_SW', 'Ukraine'),
  ('UMI_NE', 'U.S. Minor Outlying Is.'),
  ('UMI_NW', 'U.S. Minor Outlying Is.'),
  ('UMI_SE', 'U.S. Minor Outlying Is.'),
  ('UMI_SW', 'U.S. Minor Outlying Is.'),
  ('URY_NE', 'Uruguay'),
  ('URY_NW', 'Uruguay'),
  ('URY_SE', 'Uruguay'),
  ('URY_SW', 'Uruguay'),
  ('USA_NE', 'United States of America'),
  ('USA_NW', 'United States of America'),
  ('USA_SE', 'United States of America'),
  ('USA_SW', 'United States of America'),
  ('USG_NE', 'USNB Guantanamo Bay'),
  ('USG_NW', 'USNB Guantanamo Bay'),
  ('USG_SE', 'USNB Guantanamo Bay'),
  ('USG_SW', 'USNB Guantanamo Bay'),
  ('UZB_NE', 'Uzbekistan'),
  ('UZB_NW', 'Uzbekistan'),
  ('UZB_SE', 'Uzbekistan'),
  ('UZB_SW', 'Uzbekistan'),
  ('VAT_NE', 'Vatican'),
  ('VAT_NW', 'Vatican'),
  ('VAT_SE', 'Vatican'),
  ('VAT_SW', 'Vatican'),
  ('VCT_NE', 'St. Vin. and Gren.'),
  ('VCT_NW', 'St. Vin. and Gren.'),
  ('VCT_SE', 'St. Vin. and Gren.'),
  ('VCT_SW', 'St. Vin. and Gren.'),
  ('VEN_NE', 'Venezuela'),
  ('VEN_NW', 'Venezuela'),
  ('VEN_SE', 'Venezuela'),
  ('VEN_SW', 'Venezuela'),
  ('VGB_NE', 'British Virgin Is.'),
  ('VGB_NW', 'British Virgin Is.'),
  ('VGB_SE', 'British Virgin Is.'),
  ('VGB_SW', 'British Virgin Is.'),
  ('VIR_NE', 'U.S. Virgin Is.'),
  ('VIR_NW', 'U.S. Virgin Is.'),
  ('VIR_SE', 'U.S. Virgin Is.'),
  ('VIR_SW', 'U.S. Virgin Is.'),
  ('VNM_NE', 'Vietnam'),
  ('VNM_NW', 'Vietnam'),
  ('VNM_SE', 'Vietnam'),
  ('VNM_SW', 'Vietnam'),
  ('VUT_NE', 'Vanuatu'),
  ('VUT_NW', 'Vanuatu'),
  ('VUT_SE', 'Vanuatu'),
  ('VUT_SW', 'Vanuatu'),
  ('WLF_NE', 'Wallis and Futuna Is.'),
  ('WLF_NW', 'Wallis and Futuna Is.'),
  ('WLF_SE', 'Wallis and Futuna Is.'),
  ('WLF_SW', 'Wallis and Futuna Is.'),
  ('WSB_NE', 'Akrotiri'),
  ('WSB_NW', 'Akrotiri'),
  ('WSB_SE', 'Akrotiri'),
  ('WSB_SW', 'Akrotiri'),
  ('WSM_NE', 'Samoa'),
  ('WSM_NW', 'Samoa'),
  ('WSM_SE', 'Samoa'),
  ('WSM_SW', 'Samoa'),
  ('YEM_NE', 'Yemen'),
  ('YEM_NW', 'Yemen'),
  ('YEM_SE', 'Yemen'),
  ('YEM_SW', 'Yemen'),
  ('ZAF_NE', 'South Africa'),
  ('ZAF_NW', 'South Africa'),
  ('ZAF_SE', 'South Africa'),
  ('ZAF_SW', 'South Africa'),
  ('ZMB_NE', 'Zambia'),
  ('ZMB_NW', 'Zambia'),
  ('ZMB_SE', 'Zambia'),
  ('ZMB_SW', 'Zambia'),
  ('ZWE_NE', 'Zimbabwe'),
  ('ZWE_NW', 'Zimbabwe'),
  ('ZWE_SE', 'Zimbabwe'),
  ('ZWE_SW', 'Zimbabwe')
on conflict (region_id) do update set country = excluded.country;

-- ── 2) war_spawn: server picks a RANDOM unclaimed region (ignores p_region) ───
-- Signature unchanged so the deployed client keeps working; p_region/p_country are
-- now IGNORED — the server draws the region from the unclaimed pool. Mirrors the
-- 047 body (1h shield) otherwise. Race-safe: re-checks ownership after the claim.
create or replace function public.war_spawn(p_region text, p_country text, p_color text, p_name text)
returns text language plpgsql security definer set search_path = public as $$
declare uid uuid := auth.uid(); existing text; v_region text; v_country text;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  -- idempotent: already enrolled -> return existing spawn
  select spawn_region into existing from public.war_players where user_id = uid;
  if existing is not null then return existing; end if;

  -- SERVER-CHOSEN random spawn from the unclaimed pool (anti "place yourself anywhere")
  select p.region_id, p.country into v_region, v_country
  from public.war_region_pool p
  where not exists (
    select 1 from public.war_regions r where r.region_id = p.region_id and r.owner_id is not null
  )
  order by random() limit 1;
  if v_region is null then raise exception 'world full'; end if;

  insert into public.war_players (user_id, display_name, color, spawn_region, shield_until, last_income_at, last_active_at)
  values (uid, p_name, p_color, v_region, now() + interval '1 hour', now(), now())
  on conflict (user_id) do nothing;
  insert into public.war_regions (region_id, country_code, owner_id, owner_name, color, is_hq, soldier, tank, jet, warship, updated_at)
  values (v_region, v_country, uid, p_name, p_color, true, 500, 0, 0, 0, now())
  on conflict (region_id) do update
    set owner_id = excluded.owner_id, owner_name = excluded.owner_name, color = excluded.color,
        is_hq = true, soldier = 500, updated_at = now()
    where public.war_regions.owner_id is null;
  -- lost a concurrent race for v_region? roll back the player insert too.
  if not exists (select 1 from public.war_regions where region_id = v_region and owner_id = uid) then
    raise exception 'spawn race, retry';
  end if;
  return v_region;
end;
$$;
revoke all on function public.war_spawn(text,text,text,text) from public;
grant execute on function public.war_spawn(text,text,text,text) to authenticated;

-- ── 3) war_buy_units: same anti-place-anywhere fix on the RESPAWN branch ──────
-- Faithful copy of the migration 052 body; the ONLY change is that respawn no longer
-- trusts p_region — the server draws a random unclaimed region (v_target). The normal
-- branch still targets the province you own (p_region). 055 applies after 052, so this
-- definition wins. Constants stay in sync with src/war/{units,economy,buildings}.js.
create or replace function public.war_buy_units(p_region text, p_type text, p_count integer)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  uid         uuid := auth.uid();
  v_unit_cost integer;
  v_strength  numeric;
  v_factory   integer;
  v_army_mult numeric;
  v_cost_mult numeric;
  v_cost      numeric;   -- numeric (not int): absurd orders overflow int4 before the
                          -- 'insufficient coins' check; balance>=v_cost keeps it in range.
  v_owned     integer;
  v_balance   integer;
  v_name      text;
  v_color     text;
  v_target    text;
begin
  if uid is null then raise exception 'not authenticated'; end if;
  if p_count is null or p_count < 1 then raise exception 'invalid count'; end if;
  if p_type not in ('soldier','tank','jet','warship') then raise exception 'invalid unit type'; end if;

  v_unit_cost := case p_type when 'soldier' then 100 when 'tank' then 400 when 'jet' then 800 when 'warship' then 4000 end;

  select coalesce(sum(soldier * 1 + tank * 5 + jet * 3 + warship * 20), 0)
    into v_strength from public.war_regions where owner_id = uid;
  v_army_mult := 1 + 0.25 * floor(v_strength / 2500);

  select coalesce(sum(level), 0) into v_factory from public.war_buildings where owner_id = uid and type = 'factory';
  v_cost_mult := greatest(0.5, 1 - 0.1 * v_factory);

  v_cost := round((v_unit_cost::numeric * p_count) * v_cost_mult * v_army_mult);

  select count(*) into v_owned from public.war_regions where owner_id = uid;

  if v_owned = 0 then
    -- respawn: SERVER picks the region (anti "place yourself anywhere"). p_region ignored.
    if p_type = 'warship' then raise exception 'warships require a port'; end if;
    select p.region_id into v_target
    from public.war_region_pool p
    where not exists (select 1 from public.war_regions r where r.region_id = p.region_id and r.owner_id is not null)
    order by random() limit 1;
    if v_target is null then raise exception 'world full'; end if;
    select display_name, color into v_name, v_color from public.war_players where user_id = uid;
  else
    v_target := p_region;
    if not exists (select 1 from public.war_regions where region_id = v_target and owner_id = uid for update) then
      raise exception 'you do not own this province';
    end if;
    if p_type = 'warship' and not exists (
      select 1 from public.war_buildings where region_id = v_target and owner_id = uid and type = 'port'
    ) then raise exception 'warships require a port in this province'; end if;
  end if;

  update public.wallets set balance = balance - v_cost
    where user_id = uid and balance >= v_cost
    returning balance into v_balance;
  if not found then raise exception 'insufficient coins'; end if;

  if v_owned = 0 then
    insert into public.war_regions (region_id, owner_id, owner_name, color, is_hq, soldier, tank, jet, warship, updated_at)
    values (v_target, uid, v_name, v_color, true, 0, 0, 0, 0, now())
    on conflict (region_id) do update
      set owner_id = excluded.owner_id, owner_name = excluded.owner_name, color = excluded.color,
          is_hq = true, soldier = 0, tank = 0, jet = 0, warship = 0, updated_at = now()
      where public.war_regions.owner_id is null;
    if not exists (select 1 from public.war_regions where region_id = v_target and owner_id = uid) then
      raise exception 'region taken';
    end if;
  end if;

  update public.war_regions set
    soldier = soldier + (case when p_type = 'soldier' then p_count else 0 end),
    tank    = tank    + (case when p_type = 'tank'    then p_count else 0 end),
    jet     = jet     + (case when p_type = 'jet'     then p_count else 0 end),
    warship = warship + (case when p_type = 'warship' then p_count else 0 end),
    updated_at = now()
  where region_id = v_target and owner_id = uid;

  return jsonb_build_object('balance', v_balance, 'region', v_target);
end; $$;
revoke all on function public.war_buy_units(text,text,integer) from public;
grant execute on function public.war_buy_units(text,text,integer) to authenticated;
